"""empty message

Revision ID: 340240a76d78
Revises: 
Create Date: 2023-11-25 15:42:59.892620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '340240a76d78'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('session_token',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('jti', sa.String(length=80), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('jti')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('session_token')
    op.drop_table('user')
    # ### end Alembic commands ###
